codecov:
  token: 98f90116-fe9b-4482-b63f-7e05ead3e6c1

coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        flags:
          - frontend
          - ui
